<?php

function crada_help($section) {
  switch ($section) {
    case 'admin/help#hello_world':
      $output = '<p>Hello world help...</p>';
      return $output;
    case 'admin/modules#description':
      return 'Hello world module description...';
  }
}

/**
 * Implementation of hook_menu().
 */
function crada_menu() {
  $items = array();
    $items['crada/new_document'] = array(
      'path' => 'crada/new_document', 
      'title' => '', 
      'page callback' => 'crada_new_document', 
			'access callback' => 'user_access',
	    'access arguments' => array('build document'),
      'type' => MENU_CALLBACK,
      'file' => 'new_document.inc',
    );
    $items['crada/current_document'] = array(
      'path' => 'crada/load_document', 
      'title' => '', 
      'page callback' => 'crada_current_document', 
			'access callback' => 'user_access',
	    'access arguments' => array('build document'),
      'type' => MENU_CALLBACK,
      'file' => 'current_document.inc',
    );
    $items['crada/search_documents'] = array(
      'path' => 'crada/search_documents', 
      'title' => '', 
      'page callback' => 'crada_search_documents', 
			'access callback' => 'user_access',
	    'access arguments' => array('build document'),
      'type' => MENU_CALLBACK,
      'file' => 'search_document.inc',
    );
    
    $items['crada/clear_database'] = array(
		'path' => 'crada/clear_database', 
		'title' => '', 
		'page callback' => 'drupal_get_form',
		'page arguments' => array('clean_tables_form'),
		'access callback' => 'user_access',
    'access arguments' => array('master document'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'clean_tables.inc',
    );
    $items['crada/master_document'] = array(
		'path' => 'crada/master_document', 
		'title' => '', 
		'page callback' => 'drupal_get_form',
		'page arguments' => array('master_document_form'),
		'access callback' => 'user_access',
    'access arguments' => array('master document'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'master_document.inc',
    );
 
    $items['crada/server'] = array(
		'path' => 'crada/server', 
		'title' => '', 
		'page callback' => 'crada_server',
		'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM,
		'file' => 'crada_server.inc',
    );

    $items['crada/download_document'] = array(
    'path' => 'crada/download_document', 
    'title' => '', 
    'page callback' => 'download_document',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'download_document.inc',
    );
    
  return $items;
}

function crada_permission() {
  return array(
    'master document' => array(
      'title' => t('CRADA Load Master Document'),
      'description' => t('Load a Master Document into the database'),
    ),
    'build document' => array(
      'title' => t('CRADA Build New Document'),
      'description' => t('Create a new Master Document'),
    ),
  );
}