<?php

function crada_help($section) {
  switch ($section) {
    case 'admin/help#hello_world':
      $output = '<p>Hello world help...</p>';
      return $output;
    case 'admin/modules#description':
      return 'Hello world module description...';
  }
}

/**
 * Implementation of hook_menu().
 */
function crada_menu() {
  $items = array();
    $items['crada/new_document'] = array(
      'path' => 'crada/new_document', 
      'title' => '', 
      'page callback' => 'crada_new_document', 
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
      'file' => 'document_builder.inc',
    );
    $items['crada/current_document'] = array(
      'path' => 'crada/load_document', 
      'title' => '', 
      'page callback' => 'crada_current_document', 
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
      'file' => 'document_builder.inc',
    );
    $items['crada/search_documents'] = array(
      'path' => 'crada/search_documents', 
      'title' => '', 
      'page callback' => 'crada_search_documents', 
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
      'file' => 'document_builder.inc',
    );
    
    $items['crada/clear_database'] = array(
		'path' => 'crada/clear_database', 
		'title' => '', 
		'page callback' => 'drupal_get_form',
		'page arguments' => array('clean_tables_form'),
		'access callback' => 'user_access',
        'access arguments' => array('administrator'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'clean_tables.inc',
    );
    $items['crada/master_document'] = array(
		'path' => 'crada/master_document', 
		'title' => '', 
		'page callback' => 'drupal_get_form',
		'page arguments' => array('master_document_form'),
		'access callback' => 'user_access',
        'access arguments' => array('administrator'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'master_document.inc',
    );
    
  return $items;
}

/**
 * Function which generate page (this generate any content - you need only your own code...)
 */

